- op: add
  path: /spec/template/spec/containers/-
  value: 
    name: telegraf
    image: docker.io/library/telegraf:1.9.5-alpine
    volumeMounts:
      - name: telegraf-pingfederate-config
        mountPath: /etc/telegraf
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi