apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
spec:
  selector:
    matchLabels:
      app: jmeter
  replicas: 1
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
      - name: jmeter
        image: pingidentity/apache-jmeter:edge
        command: ["/bin/sh", "-c"]
        args:
          - echo cloning repo;
            git clone https://github.com/mdeller-ping/tpc-poc.git;
            ls -l; 
            pwd;
            cat giterized-entrypoint.sh;
            echo;
            env;
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: jmeter-variables
        
