apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    name: pf-cluster-console
    labels:
      app: pf-cluster
      tier: frontend
  spec:
    replicas: 1
    selector:
        matchLabels:
          app: pf-cluster
          tier: frontend
    template:
      metadata:
        labels:
          app: pf-cluster
          tier: frontend
      spec:
        containers:
        - name: console-node
          image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-centos-edge
          ports:
          - containerPort: 9999
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: console-variables
            - secretRef:
                name: devops-secret
                optional: true
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    name: pf-cluster-engine
    labels:
      app: pf-cluster
      tier: backend
  spec:
    replicas: 2
    selector:
        matchLabels:
          app: pf-cluster
          tier: backend
    template:
      metadata:
        labels:
          app: pf-cluster
          tier: backend
      spec:
        containers:
        - name: engine-node
          image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-centos-edge
          ports:
          - containerPort: 9031
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: engine-variables
            - secretRef:
                name: devops-secret
                optional: true
kind: List
metadata: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pf-cluster-dns
  labels:
    run: pf-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
      targetPort: 7600
  selector:
     app: pf-cluster
---
apiVersion: v1
kind: Service
metadata:
    name: pf-admin-loadbalancer
    labels:
        run: pf-cluster
        tier: frontend
spec:
    ports:
        - name: admin-port
          port: 9999
          protocol: TCP
          targetPort: 9999
    selector:
        app: pf-cluster
        tier: frontend
---
apiVersion: v1
kind: Service
metadata:
    name: pf-engine-loadbalancer
    labels:
        run: pf-cluster
        tier: backend
spec:
    ports:
        - name: engine-port
          port: 9031
          protocol: TCP
          targetPort: 9031
    selector:
        app: pf-cluster
        tier: backend
