kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingfederate.yaml

# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-environment-variables
  env: env_vars.pingfederate
- name: pingfederate-engine-environment-variables
  env: env_vars.pingfederate-engine
