apiVersion: v1
kind: Service
metadata:
  name: pingfederate-console-loadbalancer
spec:
  selector:
    app: pingfederate-console
  ports:
    - port: 9999
      name: pingfederate-console
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pingfederate-engine-loadbalancer
spec:
  selector:
    app: pingfederate-engine
  ports:
    - port: 9031
      name: pingfederate-engine
      targetPort: 9031
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pingfederate-dns
  labels:
    run: pingfederate
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
      targetPort: 7600
  selector:
    app: pingfederate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfederate
  template:
    metadata:
      name: pingfederate
      labels:
        app: pingfederate
    spec:
      containers:
        - name: pingfederate-console
          image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-alpine-edge
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: pingfederate-console-variables
            - secretRef:
                name: devops-secret
                optional: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingfederate
  template:
    metadata:
      name: pingfederate
      labels:
        app: pingfederate
    spec:
      containers:
        - name: pingfederate-engine
          image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-alpine-edge
          ports:
            - containerPort: 9031
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: pingfederate-engine-variables
            - secretRef:
                name: devops-secret
                optional: true
